-- MySQL Script generated by MySQL Workbench
-- 12/28/16 21:14:11
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb_forum
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb_forum
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb_forum` DEFAULT CHARACTER SET utf8 ;
USE `mydb_forum` ;

-- -----------------------------------------------------
-- Table `mydb_forum`.`admin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb_forum`.`admin` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `adminname` VARCHAR(45) NULL COMMENT '管理员名称',
  `createtime` TIMESTAMP NULL DEFAULT current_timestamp COMMENT '该管理员创建的时间',
  `password` VARCHAR(45) NULL COMMENT '管理员密码',
  `email` VARCHAR(45) NULL COMMENT '创建时预留邮箱',
  `phone` VARCHAR(20) NULL COMMENT '创建时预留手机号',
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
