-- MySQL Script generated by MySQL Workbench
-- 08/06/17 11:57:08
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema my_library
-- -----------------------------------------------------
-- 借书系统项目数据库

-- -----------------------------------------------------
-- Schema my_library
--
-- 借书系统项目数据库
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `my_library` DEFAULT CHARACTER SET utf8 ;
USE `my_library` ;

-- -----------------------------------------------------
-- Table `my_library`.`admin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `my_library`.`admin` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `a_name` VARCHAR(45) NOT NULL COMMENT '管理员名',
  `a_password` VARCHAR(45) NOT NULL COMMENT '管理员密码',
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `my_library`.`book`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `my_library`.`book` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `b_name` VARCHAR(45) NULL COMMENT '书名',
  `b_author` VARCHAR(45) NULL COMMENT '作者',
  `b_press` VARCHAR(45) NULL COMMENT '出版社',
  `total` INT NULL COMMENT '总数',
  `current_num` INT NULL COMMENT '当前剩余数量',
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `my_library`.`library_card`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `my_library`.`library_card` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL COMMENT '借卡人姓名',
  `phone` VARCHAR(11) NULL COMMENT '借卡人联系方式',
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `my_library`.`book_library_card`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `my_library`.`book_library_card` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `borrow_date` TIMESTAMP NULL DEFAULT current_timestamp COMMENT '借书时间',
  `library_card_id` INT NOT NULL,
  `book_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_book_library_card_library_card_idx` (`library_card_id` ASC),
  INDEX `fk_book_library_card_book1_idx` (`book_id` ASC),
  CONSTRAINT `fk_book_library_card_library_card`
    FOREIGN KEY (`library_card_id`)
    REFERENCES `my_library`.`library_card` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_book_library_card_book1`
    FOREIGN KEY (`book_id`)
    REFERENCES `my_library`.`book` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
